# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: rendu-git.etna-alternance.net:5040/module-5130/activity-30494/group-690332/worko
  name: webapp
  tag: 0.0.1
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080
